application: mywebutilities
version: 2
runtime: python
api_version: 1

handlers:
- url: /Admin.py
  script: Admin.py
  login: admin
- url: /
  static_files: Admin.html
  upload: Admin.html
  login: admin
- url: /Admin.js
  static_files: Admin.js
  upload: Admin.js
  login: admin
- url: /GetUtf8Page.*
  script: launchPage.py
- url: /RemoveDesc.*
  script: launchPage.py
- url: /RefChange.*
  script: launchPage.py
- url: /EPage.html
  static_files: EPage.html
  upload: EPage.html
- url: /UpdateIP.py
  script: launchPage.py
  login: admin
- url: /UpdateIP.html
  static_files: UpdateIP.html
  upload: UpdateIP.html
  login: admin
- url: /js
  static_dir: js
- url: /static
  static_dir: static 
